# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'configwindow.ui'
#
# Created: Sat Jul 14 22:19:36 2012
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(481, 261)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainLabel = QtGui.QLabel(Dialog)
        self.mainLabel.setObjectName("mainLabel")
        self.verticalLayout.addWidget(self.mainLabel)
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.accountTab = QtGui.QWidget()
        self.accountTab.setObjectName("accountTab")
        self.formLayout_3 = QtGui.QFormLayout(self.accountTab)
        self.formLayout_3.setObjectName("formLayout_3")
        self.emailLabel = QtGui.QLabel(self.accountTab)
        self.emailLabel.setObjectName("emailLabel")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.emailLabel)
        self.emailLine = QtGui.QLineEdit(self.accountTab)
        self.emailLine.setObjectName("emailLine")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.emailLine)
        self.passwdLabel = QtGui.QLabel(self.accountTab)
        self.passwdLabel.setObjectName("passwdLabel")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.passwdLabel)
        self.passwdLine = QtGui.QLineEdit(self.accountTab)
        self.passwdLine.setEchoMode(QtGui.QLineEdit.Password)
        self.passwdLine.setObjectName("passwdLine")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.passwdLine)
        self.connectLabel = QtGui.QLabel(self.accountTab)
        self.connectLabel.setObjectName("connectLabel")
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.connectLabel)
        self.connectBox = QtGui.QCheckBox(self.accountTab)
        self.connectBox.setText("")
        self.connectBox.setObjectName("connectBox")
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.connectBox)
        self.tabWidget.addTab(self.accountTab, "")
        self.dataTab = QtGui.QWidget()
        self.dataTab.setObjectName("dataTab")
        self.formLayout = QtGui.QFormLayout(self.dataTab)
        self.formLayout.setObjectName("formLayout")
        self.saveCsvLabel = QtGui.QLabel(self.dataTab)
        self.saveCsvLabel.setObjectName("saveCsvLabel")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.saveCsvLabel)
        self.saveCsvBox = QtGui.QCheckBox(self.dataTab)
        self.saveCsvBox.setText("")
        self.saveCsvBox.setChecked(True)
        self.saveCsvBox.setObjectName("saveCsvBox")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.saveCsvBox)
        self.csvPathLabel = QtGui.QLabel(self.dataTab)
        self.csvPathLabel.setObjectName("csvPathLabel")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.csvPathLabel)
        self.csvPathLine = QtGui.QLineEdit(self.dataTab)
        self.csvPathLine.setObjectName("csvPathLine")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.csvPathLine)
        self.csvFormatLabel = QtGui.QLabel(self.dataTab)
        self.csvFormatLabel.setObjectName("csvFormatLabel")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.csvFormatLabel)
        self.csvFormatLine = QtGui.QLineEdit(self.dataTab)
        self.csvFormatLine.setObjectName("csvFormatLine")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.csvFormatLine)
        self.saveXmlBox_2 = QtGui.QLabel(self.dataTab)
        self.saveXmlBox_2.setObjectName("saveXmlBox_2")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.saveXmlBox_2)
        self.saveXmlBox = QtGui.QCheckBox(self.dataTab)
        self.saveXmlBox.setText("")
        self.saveXmlBox.setChecked(True)
        self.saveXmlBox.setObjectName("saveXmlBox")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.saveXmlBox)
        self.xmlPathLabel = QtGui.QLabel(self.dataTab)
        self.xmlPathLabel.setObjectName("xmlPathLabel")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.xmlPathLabel)
        self.xmlPathLine = QtGui.QLineEdit(self.dataTab)
        self.xmlPathLine.setObjectName("xmlPathLine")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.xmlPathLine)
        self.tabWidget.addTab(self.dataTab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.emailLabel.setBuddy(self.emailLine)
        self.passwdLabel.setBuddy(self.passwdLine)
        self.connectLabel.setBuddy(self.connectBox)
        self.saveCsvLabel.setBuddy(self.saveCsvBox)
        self.csvPathLabel.setBuddy(self.csvPathLine)
        self.csvFormatLabel.setBuddy(self.csvFormatLine)
        self.saveXmlBox_2.setBuddy(self.saveXmlBox)
        self.xmlPathLabel.setBuddy(self.xmlPathLine)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QObject.connect(self.saveCsvBox, QtCore.SIGNAL("toggled(bool)"), self.csvPathLine.setEnabled)
        QtCore.QObject.connect(self.saveCsvBox, QtCore.SIGNAL("toggled(bool)"), self.csvFormatLine.setEnabled)
        QtCore.QObject.connect(self.saveXmlBox, QtCore.SIGNAL("toggled(bool)"), self.xmlPathLine.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.mainLabel.setText(QtGui.QApplication.translate("Dialog", "miCoach backup - Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.emailLabel.setText(QtGui.QApplication.translate("Dialog", "Email", None, QtGui.QApplication.UnicodeUTF8))
        self.passwdLabel.setText(QtGui.QApplication.translate("Dialog", "Password", None, QtGui.QApplication.UnicodeUTF8))
        self.connectLabel.setText(QtGui.QApplication.translate("Dialog", "Connect at startup", None, QtGui.QApplication.UnicodeUTF8))
        self.connectBox.setToolTip(QtGui.QApplication.translate("Dialog", "Start connection at startup", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.accountTab), QtGui.QApplication.translate("Dialog", "Account", None, QtGui.QApplication.UnicodeUTF8))
        self.saveCsvLabel.setText(QtGui.QApplication.translate("Dialog", "Save CSV", None, QtGui.QApplication.UnicodeUTF8))
        self.csvPathLabel.setText(QtGui.QApplication.translate("Dialog", "CSV path", None, QtGui.QApplication.UnicodeUTF8))
        self.csvFormatLabel.setText(QtGui.QApplication.translate("Dialog", "CSV lines format    ", None, QtGui.QApplication.UnicodeUTF8))
        self.saveXmlBox_2.setText(QtGui.QApplication.translate("Dialog", "Save raw XML", None, QtGui.QApplication.UnicodeUTF8))
        self.xmlPathLabel.setText(QtGui.QApplication.translate("Dialog", "XML path", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.dataTab), QtGui.QApplication.translate("Dialog", "Data", None, QtGui.QApplication.UnicodeUTF8))

