# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Sun Jul 15 00:27:57 2012
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(476, 243)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.titleLabel = QtGui.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(16)
        font.setWeight(75)
        font.setBold(True)
        self.titleLabel.setFont(font)
        self.titleLabel.setObjectName("titleLabel")
        self.horizontalLayout_2.addWidget(self.titleLabel)
        self.configButton = QtGui.QPushButton(self.centralWidget)
        self.configButton.setMaximumSize(QtCore.QSize(50, 50))
        self.configButton.setBaseSize(QtCore.QSize(25, 25))
        self.configButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/configuration.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.configButton.setIcon(icon1)
        self.configButton.setFlat(True)
        self.configButton.setObjectName("configButton")
        self.horizontalLayout_2.addWidget(self.configButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.viewPages = QtGui.QStackedWidget(self.centralWidget)
        self.viewPages.setObjectName("viewPages")
        self.connectPage = QtGui.QWidget()
        self.connectPage.setObjectName("connectPage")
        self.gridLayout_2 = QtGui.QGridLayout(self.connectPage)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.connectInstructionsLabel = QtGui.QLabel(self.connectPage)
        self.connectInstructionsLabel.setObjectName("connectInstructionsLabel")
        self.gridLayout_2.addWidget(self.connectInstructionsLabel, 0, 0, 1, 2)
        self.emailLabel = QtGui.QLabel(self.connectPage)
        self.emailLabel.setObjectName("emailLabel")
        self.gridLayout_2.addWidget(self.emailLabel, 1, 0, 1, 1)
        self.emailLine = QtGui.QLineEdit(self.connectPage)
        self.emailLine.setObjectName("emailLine")
        self.gridLayout_2.addWidget(self.emailLine, 1, 1, 1, 1)
        self.passwordLabel = QtGui.QLabel(self.connectPage)
        self.passwordLabel.setObjectName("passwordLabel")
        self.gridLayout_2.addWidget(self.passwordLabel, 2, 0, 1, 1)
        self.passwordLine = QtGui.QLineEdit(self.connectPage)
        self.passwordLine.setEchoMode(QtGui.QLineEdit.Password)
        self.passwordLine.setObjectName("passwordLine")
        self.gridLayout_2.addWidget(self.passwordLine, 2, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(376, 3, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 5, 1, 1, 1)
        self.forgotPasswordLabel = QtGui.QLabel(self.connectPage)
        self.forgotPasswordLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.forgotPasswordLabel.setOpenExternalLinks(True)
        self.forgotPasswordLabel.setObjectName("forgotPasswordLabel")
        self.gridLayout_2.addWidget(self.forgotPasswordLabel, 3, 1, 1, 1)
        self.loadingIcon = QtGui.QLabel(self.connectPage)
        self.loadingIcon.setText("")
        self.loadingIcon.setPixmap(QtGui.QPixmap(":/reload.png"))
        self.loadingIcon.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.loadingIcon.setObjectName("loadingIcon")
        self.gridLayout_2.addWidget(self.loadingIcon, 4, 0, 1, 1)
        self.loadingLabel = QtGui.QLabel(self.connectPage)
        self.loadingLabel.setObjectName("loadingLabel")
        self.gridLayout_2.addWidget(self.loadingLabel, 4, 1, 1, 1)
        self.viewPages.addWidget(self.connectPage)
        self.choosePage = QtGui.QWidget()
        self.choosePage.setObjectName("choosePage")
        self.chooseVLayout = QtGui.QVBoxLayout(self.choosePage)
        self.chooseVLayout.setObjectName("chooseVLayout")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.chooseInstructionsIcon = QtGui.QLabel(self.choosePage)
        self.chooseInstructionsIcon.setText("")
        self.chooseInstructionsIcon.setPixmap(QtGui.QPixmap(":/reload.png"))
        self.chooseInstructionsIcon.setObjectName("chooseInstructionsIcon")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.chooseInstructionsIcon)
        self.chooseInstructionsLabel = QtGui.QLabel(self.choosePage)
        self.chooseInstructionsLabel.setObjectName("chooseInstructionsLabel")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.chooseInstructionsLabel)
        self.chooseVLayout.addLayout(self.formLayout)
        self.viewPages.addWidget(self.choosePage)
        self.downloadPage = QtGui.QWidget()
        self.downloadPage.setObjectName("downloadPage")
        self.gridLayout_3 = QtGui.QGridLayout(self.downloadPage)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.downloadInfosLabel = QtGui.QLabel(self.downloadPage)
        self.downloadInfosLabel.setObjectName("downloadInfosLabel")
        self.gridLayout_3.addWidget(self.downloadInfosLabel, 0, 0, 1, 1)
        self.progressBar = QtGui.QProgressBar(self.downloadPage)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_3.addWidget(self.progressBar, 2, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 1, 0, 1, 1)
        self.progressLabel = QtGui.QLabel(self.downloadPage)
        self.progressLabel.setObjectName("progressLabel")
        self.gridLayout_3.addWidget(self.progressLabel, 3, 0, 1, 1)
        self.viewPages.addWidget(self.downloadPage)
        self.verticalLayout.addWidget(self.viewPages)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cancelButton = QtGui.QPushButton(self.centralWidget)
        self.cancelButton.setEnabled(True)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.previousButton = QtGui.QPushButton(self.centralWidget)
        self.previousButton.setObjectName("previousButton")
        self.horizontalLayout.addWidget(self.previousButton)
        self.nextButton = QtGui.QPushButton(self.centralWidget)
        self.nextButton.setObjectName("nextButton")
        self.horizontalLayout.addWidget(self.nextButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.viewPages.setCurrentIndex(0)
        QtCore.QObject.connect(self.passwordLine, QtCore.SIGNAL("returnPressed()"), self.nextButton.click)
        QtCore.QObject.connect(self.emailLine, QtCore.SIGNAL("returnPressed()"), self.nextButton.click)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.emailLine, self.passwordLine)
        MainWindow.setTabOrder(self.passwordLine, self.nextButton)
        MainWindow.setTabOrder(self.nextButton, self.previousButton)
        MainWindow.setTabOrder(self.previousButton, self.cancelButton)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "miCoach backup", None, QtGui.QApplication.UnicodeUTF8))
        self.titleLabel.setText(QtGui.QApplication.translate("MainWindow", "miCoach backup", None, QtGui.QApplication.UnicodeUTF8))
        self.connectInstructionsLabel.setText(QtGui.QApplication.translate("MainWindow", "Please enter your login informations", None, QtGui.QApplication.UnicodeUTF8))
        self.emailLabel.setText(QtGui.QApplication.translate("MainWindow", "Email", None, QtGui.QApplication.UnicodeUTF8))
        self.passwordLabel.setText(QtGui.QApplication.translate("MainWindow", "Password", None, QtGui.QApplication.UnicodeUTF8))
        self.forgotPasswordLabel.setText(QtGui.QApplication.translate("MainWindow", "Forgot Password?", None, QtGui.QApplication.UnicodeUTF8))
        self.loadingLabel.setText(QtGui.QApplication.translate("MainWindow", "Loading...", None, QtGui.QApplication.UnicodeUTF8))
        self.chooseInstructionsLabel.setText(QtGui.QApplication.translate("MainWindow", "Select workouts to be downloaded. ", None, QtGui.QApplication.UnicodeUTF8))
        self.downloadInfosLabel.setText(QtGui.QApplication.translate("MainWindow", "Downloading selected files", None, QtGui.QApplication.UnicodeUTF8))
        self.progressLabel.setText(QtGui.QApplication.translate("MainWindow", "Downloading file 0 of 0", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelButton.setText(QtGui.QApplication.translate("MainWindow", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.previousButton.setText(QtGui.QApplication.translate("MainWindow", "Previous", None, QtGui.QApplication.UnicodeUTF8))
        self.nextButton.setText(QtGui.QApplication.translate("MainWindow", "Next", None, QtGui.QApplication.UnicodeUTF8))

import images_rc
